Update to unit test file. Errors described below:
- 1) spiralWebDb\CornerstoneTours\Tests\Unit\Tests_SetPastToursByOrderNumber::test_should_return_unmodified_query_vars_when_post_type_archive_is_false
Mockery\Exception\InvalidCountException: Method is_post_type_archive(<No Arguments>) from Mockery_0 should be called exactly 1 times but called 0 times.
- 2) spiralWebDb\CornerstoneTours\Tests\Unit\Tests_SetPastToursByOrderNumber::test_should_modify_query_var_default_when_post_type_archive_is_true
Error: Call to a member function shouldReceive() on null ( L#74 ).